services:
  # Database
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pipesim_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:8-alpine
    container_name: pipesim_redis
    ports:
      - "6379:6379"
    restart: always

  # API
  api:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      # [IMPORTANT] Override the database URL
      # These is no localhost (127.0.0.1) inside the Docker network. The API should knock on the 'db' service name
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/pipesim_db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
  worker:
    build: .
    container_name: pipesim_worker
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/pipesim_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    
  frontend:
    build:
      context: ./frontend
    container_name: pipesim_frontend
    ports:
      - "8501:8501" # Port for access from browser
    depends_on:
      - api # Starting front only after start API
    environment:
      - BACKEND_URL=http://api:8000
    volumes:
      - ./frontend:/app

# Save database settings on hard disk, so that they don't disappear when restarting
volumes:
  postgres_data: