"""Initial baseline after db reset

Revision ID: 634c673a8fc3
Revises: 
Create Date: 2026-02-21 18:39:13.161885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '634c673a8fc3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_table('passengers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('PassengerId', sa.Integer(), nullable=True),
    sa.Column('Survived', sa.Integer(), nullable=True),
    sa.Column('Pclass', sa.Integer(), nullable=True),
    sa.Column('Name', sa.String(), nullable=True),
    sa.Column('Sex', sa.String(), nullable=True),
    sa.Column('Age', sa.Float(), nullable=True),
    sa.Column('SibSp', sa.Integer(), nullable=True),
    sa.Column('Parch', sa.Integer(), nullable=True),
    sa.Column('Ticket', sa.String(), nullable=True),
    sa.Column('Fare', sa.Float(), nullable=True),
    sa.Column('Cabin', sa.String(), nullable=True),
    sa.Column('Embarked', sa.String(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passengers_PassengerId'), 'passengers', ['PassengerId'], unique=True)
    op.create_index(op.f('ix_passengers_id'), 'passengers', ['id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_data', sa.JSON(), nullable=True),
    sa.Column('prediction_result', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_id'), 'predictions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_passengers_id'), table_name='passengers')
    op.drop_index(op.f('ix_passengers_PassengerId'), table_name='passengers')
    op.drop_table('passengers')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    # ### end Alembic commands ###
