"""Add processed_features table

Revision ID: 7240a3f0517a
Revises: 634c673a8fc3
Create Date: 2026-02-21 23:51:52.713446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7240a3f0517a'
down_revision: Union[str, Sequence[str], None] = '634c673a8fc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data_hash', sa.String(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_features_id'), 'processed_features', ['id'], unique=False)
    op.create_index(op.f('ix_processed_features_raw_data_hash'), 'processed_features', ['raw_data_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_features_raw_data_hash'), table_name='processed_features')
    op.drop_index(op.f('ix_processed_features_id'), table_name='processed_features')
    op.drop_table('processed_features')
    # ### end Alembic commands ###
