"""Add is_processed column

Revision ID: b8d11a17e3f3
Revises: 2e9a8a081296
Create Date: 2026-02-19 01:01:56.569686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8d11a17e3f3'
down_revision: Union[str, Sequence[str], None] = '2e9a8a081296'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passengers', sa.Column('is_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('passengers', 'is_processed')
    # ### end Alembic commands ###
