"""Add missing key_hash column

Revision ID: c47eea2bad70
Revises: 57bdb46030d7
Create Date: 2026-02-26 12:53:06.337986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c47eea2bad70'
down_revision: Union[str, Sequence[str], None] = '57bdb46030d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_hash', sa.String(), nullable=False))
    op.drop_index(op.f('ix_api_keys_hey_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.drop_column('api_keys', 'hey_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('hey_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index(op.f('ix_api_keys_hey_hash'), 'api_keys', ['hey_hash'], unique=True)
    op.drop_column('api_keys', 'key_hash')
    # ### end Alembic commands ###
