import os
import json
from google import genai
from loguru import logger

# API KEY
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

if GEMINI_API_KEY:
    logger.warning("GEMINI_API_KEY not found in venv variables")

def generate_video_report(json_data: dict) -> str:
    """
    Sends json-statistics to Gemini API and returns text report
    """
    if not GEMINI_API_KEY:
        logger.error("Error: API key for LLM not configured")
        return "Error: API key for LLM not configured"

    # Init google client
    try:
        client = genai.Client(api_key=GEMINI_API_KEY)
    except Exception as e:
        logger.error(f"Failed to init Gemini client: {e}")
        return f"Client inti error: {e}"

    # Choise model (2.5 Flash)
    model_id = 'gemini-2.5-flash'

    # Prompt (instraction for LLM)
    system_prompt = """
    You are a professional AI analyst for computer vision systems.
    You are given a JSON log generated by the YOLO model during video processing.
    The log contains frames (or timecodes) and objects that were detected at the moment.

    Your task is to translate this raw data into a clear, detailed, and statistically accurate text report.
    The tone should be professional, analytical, and moderately free.
    Write your answer in Russian.

    CRITICAL RULES:
    - DO NOT use any greetings (e.g., "Уважаемый руководитель").
    - DO NOT use any sign-offs or conversational filler (e.g., "Надеюсь, данный отчет...").
    - Output ONLY the structured markdown report.

    The structure your report:
    1. A brief summary: What is happening in the video (in 2-3 sentences).
    2. Key statistics: What objects appeared most often, and what were the trends.
    3. Chronology: Describe the development of events over time.
    4. Conclusion/Anomalies: Pay attention to any oddities or potential violations.

    JSON:
    """

    # Convert dict to beautiful JSON-string
    json_string = json.dumps(json_data, ensure_ascii=False, indent=2)

    # Combining instructions and data
    full_prompt = f"{system_prompt}\n\n{json_string}"

    try:
        logger.info("Sending data to Gemini API for generate a report")
        # Generate a report
        response = client.models.generate_content(
            model = model_id,
            contents = full_prompt
            )
        logger.info("The LLM report has been successfully received")
        return response.text
    except Exception as e:
        logger.error(f"Error when accessing LLM: {e}")
        return f"An error occured when generating the report: {e}"